package moviereview;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mikhael AS
 */
public class MovieListForm extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement ps = null;
    
    
    
    /**
     * Creates new form MovieListForm
     */
    public MovieListForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmdMovie1 = new javax.swing.JButton();
        cmdMovie2 = new javax.swing.JButton();
        txtRating1 = new javax.swing.JLabel();
        cmdLogin = new javax.swing.JButton();
        lblRating1 = new javax.swing.JLabel();
        cmdRating = new javax.swing.JButton();
        lblRating2 = new javax.swing.JLabel();
        lblRating11 = new javax.swing.JLabel();
        cmdRating2 = new javax.swing.JButton();
        lblRating22 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Movie List");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviereview/smallerstar.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(64, 64));
        jLabel2.setMinimumSize(new java.awt.Dimension(64, 64));
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 40));

        cmdMovie1.setText("Movie 1");
        cmdMovie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMovie1ActionPerformed(evt);
            }
        });

        cmdMovie2.setText("Movie 2");
        cmdMovie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMovie2ActionPerformed(evt);
            }
        });

        cmdLogin.setText("Login Page");
        cmdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoginActionPerformed(evt);
            }
        });

        cmdRating.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmdRating.setText("Rating");
        cmdRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRatingActionPerformed(evt);
            }
        });

        cmdRating2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmdRating2.setText("Rating 2");
        cmdRating2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRating2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cmdMovie1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRating1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblRating1)
                                        .addGap(9, 9, 9))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lblRating11)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdMovie2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRating2)
                            .addComponent(cmdLogin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRating22)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(cmdRating, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmdRating2))
                        .addGap(24, 24, 24)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmdRating))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdMovie1)
                        .addComponent(lblRating1)
                        .addComponent(lblRating11))
                    .addComponent(txtRating1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdMovie2)
                    .addComponent(lblRating2)
                    .addComponent(lblRating22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdRating2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(cmdLogin)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdMovie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMovie2ActionPerformed
        RatingMovie2 r = new RatingMovie2();
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_cmdMovie2ActionPerformed

    private void cmdMovie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMovie1ActionPerformed
        RatingMovie1 r = new RatingMovie1();
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_cmdMovie1ActionPerformed

    private void cmdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoginActionPerformed
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_cmdLoginActionPerformed

    private void cmdRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRatingActionPerformed
        
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/moviereview", "root", "");
            String sql = "select AVG(user_rating) from movie1";
            
            ps = con.prepareStatement(sql);
            
            ResultSet rs = ps.executeQuery();
            
        if(rs.next()){ 
            String rating1 = rs.getString(1);
            
            lblRating11.setText(rating1);
            
            
            
            
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    
    }//GEN-LAST:event_cmdRatingActionPerformed

    private void cmdRating2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRating2ActionPerformed
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/moviereview", "root", "");
            String sql = "select AVG(user_rating) from movie2";
            
            ps = con.prepareStatement(sql);
            
            ResultSet rs = ps.executeQuery();
            
        if(rs.next()){ 
            String rating1 = rs.getString(1);
            
            lblRating22.setText(rating1);
            
            
            
            
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }//GEN-LAST:event_cmdRating2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdLogin;
    private javax.swing.JButton cmdMovie1;
    private javax.swing.JButton cmdMovie2;
    private javax.swing.JButton cmdRating;
    private javax.swing.JButton cmdRating2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblRating1;
    private javax.swing.JLabel lblRating11;
    private javax.swing.JLabel lblRating2;
    private javax.swing.JLabel lblRating22;
    private javax.swing.JLabel txtRating1;
    // End of variables declaration//GEN-END:variables
}
